# Theme settings
doks:
  baseurl:
  color_theme: red # Available themes: blue (default), green, purple, red and yellow
  header:
    logo:
      text: Coding 2
      image:
    nav:
      - item_name: Home
        item_url: "/"
      - item_name: Syllabus
        item_url: "/syllabus"
      - item_name: U1
        item_url: "/u1"
      - item_name: Capstone
        item_url: "/capstone"
      - item_name: Resources
        item_url: "/resources"
  footer:
    content:
      logo:
        text: Coding 2 Curriculum
        image:
      description: An advanced level software development curriculum used at Dobyns-Bennett HS.
      copyright: The content of this curriculum is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 License</a>.
    social_list:
      - network_name: twitter
        profile_url: "https://twitter.com/dnbailey"
      - network_name: medium
        profile_url: "https://medium.com/tribe-bytes"
      - network_name: github
        profile_url: "https://github.com/db-cs"

# SASS settings
sass:
  sass_dir: ./doks-theme/_sass
  style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: ["README.md", "CHANGELOG.md", "LICENSE", "default.md"]
permalink: /:title/
